name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [11, 12]
    name: Java ${{matrix.java}}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}
    - run: |
        echo "<settings>
          <mirrors>
            <mirror>
              <id>rubygems-releases-mirror</id>
              <name>rubygems-releases-mirror</name>
              <url>https://repo.maven.apache.org/maven2</url>
              <mirrorOf>rubygems-releases</mirrorOf>
            </mirror>
          </mirrors>
        </settings>" > ~/.m2/settings.xml
    - run: cat ~/.m2/settings.xml
    - run: mvn -B -U clean install -DskipTests
    - run: mvn -B -U test --projects all
    - run: mvn -B -U exec:java --projects all
    - run: mvn -B -U package assembly:single --projects all -DskipTests
    - run: ls -la all/target/polyglot-java.jar
    - run: java -jar all/target/polyglot-java.jar
